### PR TITLE
Travis-ci improvement

### PR DESCRIPTION
**Pull request by PvtHaggard**
I removed nose from requirements.txt as it is not a dependency and I feel it may just end up unnecessarily inflating the dev environments of users.

The travis-ci config has been updated to include the nose module. This simplifies the config and allows for new tests to be added without having to reconfigure the travis-ci config thanks to noses autotest discovery.

Removed py32 from travis-ci config. Flask does not support py32 so it has been removed. http://flask.pocoo.org/docs/0.12/python3/

### CODE REVIEW

**Comment by PvtHaggard** [comment]
If this is merged issue #23 can be closed

**Comment by brettvanderwerff** [comment]
@PvtHaggard   nice, nose seems to be simplifying things quite a bit (@makkoncept). The one thing I am wondering about though is with removing nose from the requirements.txt would that force people testing locally to have to run each test individually like we were doing before nose?

**Comment by PvtHaggard** [comment]
@brettvanderwerff While nose is useful for the development of Flaskerizer it is not a requirement, it is a development tool. The module should be released with only the modules it needs to function and no more. 

I hope I'm not stepping on your toes, this is your project and your decision.

**Comment by brettvanderwerff** [comment]
@PvtHaggard I'm new to development, so I feel my toes are not stepped on at all I just learned something from you. We can take it out of the reqs, its still nice that we are using it in the travis ci config. I think it was an interesting find and I'm glad we're getting some use out of it. Thanks again. You can be spending your time doing anything and you decided to give some of it to the flaskerizer project so I am very grateful.

**Comment by brettvanderwerff** [comment]
@PvtHaggard What is your opinion on having the "running the tests" section in the readme. Since we have testing pretty much automated with travis now, should we just cut that section of the readme out? What do people typically do?

**Comment by makkoncept** [comment]
I agree with taking nose out of the requirements. Maybe what we can do now is move _running the  tests_ section under the contribution guidelines as the people who are going to clone the repo on their local machine will run test to make sure that they did not broke anything and telling them that _nose_ is there to help them out and save some time will be good.
I can do this if you approve @brettvanderwerff .

**Comment by PvtHaggard** [comment]
If you are going to do that use nose2 instead of nose. 
Nose had been in maintenance mode for the last few years and is not actively developed. I didn't realise until this request was merged.
Nose2 should be almost a direct replacement.

**Comment by makkoncept** [comment]
Ok, i will read its documentation and will jump right into it after getting a green flag.

**Comment by brettvanderwerff** [comment]
@makkoncept go ahead and revise the readme, I think having the testing info under the contribution subheader is a good compromise that retains the testing info for people that might want it.

**Pull request merged**
