### PR TITLE
Minimized complexity of parse_links

### PR DESCRIPTION
**Pull request by avnish98**
I splitted parse_links method in structure_directory.py into two separate method:
**change_file_path and parse_links**

I added two variables:

- file_path(line=125)

- full_path(line=137)

so that the code follows the PEP guidelines

I have also changed the for loop position.

### CODE REVIEW

**Comment by brettvanderwerff** [comment]
@avnish98 I see you are passing now, how is this going?

**Comment by avnish98** [comment]
@brettvanderwerff It is going well, I am going to do some final tests today and tell you if I want to merge.
I have splitted parse_links into two methods and added some variables so that code is following PEP guidelines

**Comment by avnish98** [comment]
@brettvanderwerff I have tested these changes on a bootstrap template and **it was successful** so, I would like to merge to master branch.

**Comment by brettvanderwerff** [comment]
The code looks much, much clear. We badly needed this. Thank you so much.

I would move the print statement from the parse_links method:
"Fixing links to reflect Flask app structure, this may take several minutes...' "
to the new method "change_file_path" because change file path is the methods that changes the links. 

Also, maybe try to make the docstrings more explicit.

For every line iterated by the parse_links method, the change_file_path method  adds the string "/static/" along with a string for the appropriate subfolder to lines that contain links that should point to contents of the static folder of the Flask app.

Or something similar.

Also, what system are you running? Ubuntu? Windows?

**Comment by avnish98** [comment]
@brettvanderwerff I am running Manjaro Linux and I will implement your changes in my pull request and present the final code by tommorow

**Comment by brettvanderwerff** [comment]
@avnish98 I just asked because issue  #75 popped up when I was testing your branch on my end. I don't think its you, I think its something broke with the flaskerizer with the 18.04 environment. I was just wondering if you had an 18.04 machine to test this on or if you had any ideas about the root of the problem since we are both paying attention to this project right now.

**Comment by avnish98** [comment]
# Working on issue #74 now

**Comment by brettvanderwerff** [comment]
Looks great @avnish98. You really helped out with the organization of the code base thank you!

**Pull request merged**
