### PR TITLE
New aliases

### PR DESCRIPTION
**Pull request by avnish98**
@brettvanderwerff I encountered the infinite loop you were telling me
screenshot from 2018-09-06 10-48-54
Turns out **It was print statement(Fixing links...)** in output again and again because it was inside method change_file_path() (going through 3 for loops).
screenshot from 2018-09-06 10-49-37
So I changed its position to inside parse_links() and tested it again and **it works fine**.
screenshot from 2018-09-06 10-50-08.
I have preserved the new command line aliases we agreed on(i, n, o, p, L, S) and I am going to test flaskerizer with some more templates and get back to you if I encounter any errors,

### CODE REVIEW

**Comment by avnish98** [comment]
@brettvanderwerff So far I have tested with:
- [https://startbootstrap.com/template-overviews/coming-soon/](https://startbootstrap.com/template-overviews/coming-soon/)
- [https://startbootstrap.com/template-overviews/one-page-wonder/](https://startbootstrap.com/template-overviews/one-page-wonder/)
- [https://colorlib.com/wp/themes/shapely/](https://colorlib.com/wp/themes/shapely/)  
And so far it just haven't worked with third one but I think it is because there are no HTML files in third template(only PHP).

**Comment by brettvanderwerff** [comment]
@avnish98 I tested this on my end, it seems to work. Nice job troubleshooting! The only thing I would recommend is going with the --o flag for the output path rather that --p like you used to have. This is just because almost everything the user supplies is a path, so --p might not be the best abbreviation.

**Comment by avnish98** [comment]
@brettvanderwerff Thanks, I have changed the output path as you said.

**Comment by brettvanderwerff** [comment]
@avnish98 Nice! works well on my end I am going to merge with master and push a minor release to PYPI (we pushed the bugged one)

**Comment by avnish98** [comment]
@brettvanderwerff I am sorry for the bug I caused, I am not much experienced with open source contribution. I will keep your repository on watch, and look to resolve future issues. I learned a lot contributing to your project and as flask developer, I have also found an amazing tool to use.

**Comment by brettvanderwerff** [comment]
@avnish98 Awesome, you made some nice features along the way too. I wouldn't worry about the bug, mistakes get merged it happens. If you can think of any way to improve the flaskerizer make sure to raise an issue, especially if you are a flask developer getting feedback on what the flask people need helps a lot. Believe it or not I actually don't really know Flask. I only knew it enough to know that template integration was an issue, so let me know if there are any lacking features and hopefully this project catches on!

**Pull request merged**
