### PR TITLE
New command line aliases

### PR DESCRIPTION
**Pull request by avnish98**
Working on issue #74 
I am suggesting new flags as:
- **--TLP** for *--top-level-path*
- **--TP** for *--templates-path*
- **--N** for *--app-name*
- **--P** for *--app-path*
- **--L** for *--large-app-structure*
- **--NL** for *--no-large-app-structure*

### CODE REVIEW

**Comment by brettvanderwerff** [comment]
@avnish98 If you want to shorten the current ones, that is fine. What the issue was regarding was the development of alias flags, which are usually a one letter of two letter flag the used could use as an abbreviation for the longer flags. Like for example the user could use the flag --app-name or the flag -n to indicate the argument for app name (or something like that). Does that make sense?

**Comment by avnish98** [comment]
@brettvanderwerff okay I can think if making one letter flags but I am having an issue 
Even after I change reference of older flags to new ones, then program keeps on asking for older flags

**Comment by brettvanderwerff** [comment]
- **--top-path** for *--top-level-path*
- **--temp-path** for *--templates-path*
- **--name** for *--app-name*
- **--path** for *--app-path*
- **--large-app** for *--large-app-structure*
- **--no-large-app** for *--no-large-app-structure*
`--path` is a little ambiguous because they are all paths. `--out` is a really common flag for output directories. I would argue that `--temp-path` is ambiguous with temporary, maybe just `--templates` instead? I'm not sure about a good substitute for `--top-path`, you don't want more than one flag starting with the same letter `t` because it is going to be hard to make one/two letter abbreviations and wont be as clear, just some recommendations

**Comment by avnish98** [comment]
@brettvanderwerff I have updated the flag name and I am confused between --top-level-path and --templates-path flag. I am looking for better substitutes.

**Comment by brettvanderwerff** [comment]
@avnish98 Are you confused by the difference between theses: --top-level-path and --templates-path. If so let me know so I can describe them in a bit more detail. they are also described in the README.

**Comment by avnish98** [comment]
@brettvanderwerff  No, I was just confused with aliases.

I am thinking:
    --TOP for --top-level-path
    --TEMP for --templates-path
    --N for --app-name
    --P for --app-path
    --L for --large-app-structure
    --NL for --no-large-app-structure
If they seem nice to you, I can implement them.

**Comment by brettvanderwerff** [comment]
@avnish98 I like most of these! here is what I am thinking now based on what you put. I am thinking now that even changing some of the old flags to something easier would be good

-i for -input
    -t for -temps 
    -n for -name
    -o for -out
    -l for -large
    -s for -small

I am trying to think of what makes to most sense for abbreviations without being confusing and what would be the least annoying the type dozens of times. What do you think?

**Comment by avnish98** [comment]
@brettvanderwerff I agree, testing the app on templates was a bit of headache with these flags, I like your suggestions. I will implement those and I was also thinking to make changes in flaskerizer call in README.md. Such that you don't have to scroll left and right to view all the arguments.

**Comment by brettvanderwerff** [comment]
@avnish98 
Great! if there is a way to shorten that bit of the README without losing info that sounds awesome. The lower the barrier is for people to get started with flaskerizer the better. 

Yes I know it was a pain to type I am learning to keep things the user needs to type simple! Even naming this project Flaskerizer, in retrospect was probably not the best, but I can't change it now lol!

**Comment by avnish98** [comment]
@brettvanderwerff  If I could suggest to same something it would be Flaskerizer -> Flaskeriser.
I have mistyped alot.

**Comment by brettvanderwerff** [comment]
@avnish98 We can't change the name now, because people have linked the project under the name Flaskerizer. If you have a good way to do that you can open an issue. it is the way it is now because it is fool proof. It forces the user to open the bootstrap template and inspect whether they have to point to a different folder for the html files (which they would have to do anyways the way it runs now). One thought that i did have was to get rid of that arg and have flaskerizer automatically walk through the folder tree and count how many html files are in each folder then assign the one with the most html files to the templates_path variable. What happens when two folders have the name num of templates though? Maybe this rarely happens though. The benefit of automating this step is that we could automatically unzip the bootstrap template for the user if they dont have to open it themselves for this inspection.

**Comment by avnish98** [comment]
@brettvanderwerff I see, I understand now that why we need those two arguments separately.

**Comment by brettvanderwerff** [comment]
@avnish98 If you have a solution though or want to open an issue just so we can start thinking about it, I am all ears.

**Comment by avnish98** [comment]
@brettvanderwerff The python3.5-dev build is not giving output even after running for 10 minutes. That's strange.

**Comment by brettvanderwerff** [comment]
@avnish98 if you are talking about travis, sometimes things are qeued and it takes a long time

**Comment by avnish98** [comment]
@brettvanderwerff I am not sure if it is because of my code or something is wrong with Travis.
This is my final code and I would like to merge to master branch.

**Comment by avnish98** [comment]
@brettvanderwerff Great I my tests pass now. I have finalized the code if you agree with flag names.  

To summarize my new flags are:
- **--i** for  *--top-level-path* (or input)
- **--t** for  *--templates-path* 
- **--o** for  *--top-level-path* (or output)
- **--n** for  *--top-level-path*
- **--L** for  *--top-level-path* (it would've been difficult to differentiate between l(ell) and I(letter "i") )
- **--S** for  *--top-level-path* (complimenting uppercase L)

**Comment by brettvanderwerff** [comment]
@avnish98 I was originally proposing of having aliases for each flag (so we would have kept the old flags), but replacing them like you did is probably just fine, especially because the old flags were so bad. This is going to help make the program much more usable. Thank you for working on this issue and contributing to the project. I will get this merged and do a minor release to PYPI as soon as I get the chance. Feel free to make additional suggestions to the project by raising issues. We are always open to improvements!

**Comment by brettvanderwerff** [comment]
@avnish98  I had to roll back the PR

**Comment by brettvanderwerff** [comment]
@ its just stuck in an infinite loop with the roll back too, unfortunately I can't spend any more time on it today let me know if this is an issue for you too please.

**Comment by avnish98** [comment]
@brettvanderwerff Pytest results are working for me, let me try with some other template.

**Comment by brettvanderwerff** [comment]
@avnish98 no problem, it might be me for all I know. I know pytest passes, but when trying to run on a template locally I get stuck in a loop. The last good commit I could find was this one if you look at the commit history: 
fix flask req security issue on sep 3

68c059cd9ba07764ae6ff4969198cea815babc62

which was right before I merged the parselinks fix. I loop at 

"fixing links to reflect flask app structure..", so my guess would be that it is that method.

Sorry I can't look at this more today. I will try to over the next couple of days but it might have to wait until the weekend. 

Again, this might be my issue I don't but if you could at least confirm the problem that would help. I reverted the github to before the most recent branch fix but its still stuck in a loop for me when I run locally from the command line.

**Comment by avnish98** [comment]
@brettvanderwerff Oh okay, I working on this issue as well, you can take your time.

**Comment by brettvanderwerff** [comment]
@avnish98 awesome, my guess would be its something simple that got shifted on the last commit of the parse links fix PR (although again it might be something I am messing up on my end too). Also just to be clear I am talking about actually running the program locally on a template not just running pytest locally. The testing isn't catching this loop.

**Comment by avnish98** [comment]
screenshot from 2018-09-05 20-44-26
I have tried it on code from fixing parse_links PR

**Comment by brettvanderwerff** [comment]
You are talking about 74eb66976cac916bc7e68692ca8f0dfdcae07439 correct? 

this is how I type it in to get the loop (assume the template is in the folder test):

`python -m flaskerizer --top-level-path .\startbootstrap-one-page-wonder-gh-pages --templates-path .\startbootstrap-one-page-wonder-gh-pages --app-path .`

im on windows which works fine on:

68c059cd9ba07764ae6ff4969198cea815babc62

**Comment by avnish98** [comment]
@brettvanderwerff Yes, you are correct I am talking about 74eb669 .
I will get back to you when I know what is the problem.

**Comment by avnish98** [comment]
@brettvanderwerff I am opening a new pull request

**Pull request merged**
