### PR TITLE
removed non-error codes from HTTP status dict

### PR DESCRIPTION
**Pull request by heberfabiano**

### CODE REVIEW

**Comment by brettvanderwerff** [comment]
@heberfabiano Welcome to the Flaskerizer. Not much review needed for this one, I think you addressed it well and we will get it merged in right away!

**Comment by brettvanderwerff** [comment]
@heberfabiano We will also get you name up in the contributors list for this PR

**Comment by heberfabiano** [comment]
Thank you @brettvanderwerff . I'm learning some new languages so I'll try to address some easy fixes like this one.

**Comment by brettvanderwerff** [comment]
@heberfabiano, of course. I am usually pretty responsive so if you have any questions about an issue you are eyeing up or if you have any suggestions for the project let me know.

**Pull request merged**
