### PR TITLE
0017 consolidate testing

### PR DESCRIPTION
**Pull request by makkoncept**
found a package named [nose](https://nose.readthedocs.io/en/latest/) that makes testing easier. We have to just run `nosetests` in top level directory and it finds all the tests and run them.
added  it to the requirements file and also i use virtual environment and hence added `venv` in the  gitignore, it is a convention.

### CODE REVIEW

**Comment by brettvanderwerff** [comment]
@makkoncept Nice solution! I tested this on my machine and it seems to work great. We just launched our travis ci integration this morning thanks to @PvtHaggard  and the nice thing about nose is that it appears that it will not disrupt any of the testing file structure that the .travis.yml file relies on. We can always back track if it does though. I was also going to say that since you have a pretty good understanding of the code base now feel free to suggest enhancements or raise issues that you think will improve the project. I don't know if you noticed or not but I made a milestone for the project in the issues. I'd like to share the project on reddit with the flask community specifically  in the near future, so any feedback on how we can make the project better in advance of that would be very welcomed!

**Comment by makkoncept** [comment]
@brettvanderwerff  i didn't saw the milestone before. It is a great one as sharing it with flask reddit will give the project more exposure. 
About the feedback and raising issues , i honestly did not test this project with other templates . i just ran it with Folio and saw that it worked pretty good and then saw some issues and jumped right into solving them. So i think i need to first test this and then i will let you know @brettvanderwerff

**Comment by makkoncept** [comment]
@brettvanderwerff  i have tested the application with some bootstrap templates from both startbootstrap.com and bootstrapmade.com 

- In some templates, while the folders are made properly and the html and styles are migrated to respective folders , when we run the localhost , we see that still some styles have not properly set and also some links are broken . therefore the user still has to do some manual work and set them.
_Some examples_  

1. [Alstar](https://bootstrapmade.com/alstar-free-parallax-bootstrap-template/)
**Original**
altstar
**Localhost**
altstar_localhost


2. The example provided with the project - [sailor template](https://bootstrapmade.com/sailor-free-bootstrap-theme/)

**Original**
sailor
**localhost**
sailor_localhost

other such templates from bootstapmade.com
- **[NiceAdmin]( https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/)**       
- **[Reveal](https://bootstrapmade.com/reveal-bootstrap-corporate-template/)**     
-  **[squadfree](https://bootstrapmade.com/squadfree-free-bootstrap-template-creative/)**


-  some of the templates from startbootsrap.com have worked **perfectly**. All the links and effects are present ,
examples -- [freelancer](https://startbootstrap.com/template-overviews/freelancer/)         [Creative](https://startbootstrap.com/template-overviews/creative/)

I will open an issue regarding the above problems with templates from bootstrapmade.com  and I think that instead of having Sailor template as an example , we should have [freelancer](https://startbootstrap.com/template-overviews/freelancer/) as one , because it shows that the _aplication is perfectly working_ with the startbootsrap.com and also this is a very popular template with over 2000 forks on [github](https://github.com/blackrockdigital/startbootstrap-freelancer/)

**Localhost version**
freelancer
I will open a Pr with the necessary changes in readme

**Comment by brettvanderwerff** [comment]
@makkoncept Sailor looks like the website example on my computer., I think it is running correctly. I think you running into the same issue that I was two days ago where I was having sailor look like you saw on localhost. When this happened I could not fix the links no matter what I tried (spent hours on it :( ). It turned out to be a browser cache issue, which might actually be more of a flask dev server thing (I don't know). But I found that you need to sometimes clear the browser cache (see readme) for things to work correctly and its not sailor specific. This usually just means clearing history and making sure to select removing browser cache. The motivation behind having folio and sailor in the project as examples was to have one template for fast testing and the other to show off the power of flaskerizer to work with a large multi-page website that would take a long time to set up manually. I think at least for now lets stick with these two examples: Sailor and Folio.

**Comment by makkoncept** [comment]
Oh, i didn't knew about the cache thing. I didn't read the readme properly, my bad. But i think that we should mention that the application works fine with startbootstrap.com , i have tested with three of their templates and all works fine . I will do it if you want and you can close PR #29 .

**Comment by brettvanderwerff** [comment]
@makkoncept i made a few comments about this this morning, but yes in general I think we have most of the templates from startbootstrap.com that I have tested working, feel free to add some comment in the readme about that.

**Comment by brettvanderwerff** [comment]
@makkoncept if you missed the cache comment in the readme other probably will too, we might need to consider bolding it or moving the warning somewhere else (or even having the program print it out) if it is a problem moving forward.

**Pull request merged**
