### PR TITLE
Added a GUI for flaskerizer

### PR DESCRIPTION
**Pull request by etiontdn**
1. I solved issue #22 making a gui using tkinter, i tried my best to add docstrings and comments but i'm not really good at it, and made a simply test that only checks if the Returned vars are OK
2. I made it in a separated file, when executed it opens a tkinter gui and lets you choose the file locations,
3. Maybe i should add a validator to validate the values since it will raise a FileNotFound error if the path is not a working path
4. In some templates it looks repititive since it selects 3 times the same folder(The example template), but it should be there for compability with other templates i think.
5. I only tested in python 3, but i think it should work in python 2 but i dont have it on my machine right now, but it should work without much of a workaround or none
3. Any Feedback is welcome

### CODE REVIEW

**Comment by etiontdn** [comment]
just checked with python 2.7.15 and 3.6 and it works fine, but checks still fail, i dont have idea why.

**Comment by brettvanderwerff** [comment]
@etiontdn Are you able to follow the details link and find the errors That TRAVIS is detecting?

**Comment by etiontdn** [comment]
Ok after a long search i found a way to make it work.
added a virtual framebuffer: XVFB so Travis servers can run tkinter

**Comment by brettvanderwerff** [comment]
@etiontdn OK great to hear. I'll take a look at the branch and give you feedback

**Comment by brettvanderwerff** [comment]
@etiontdn I really appreciate the time and effort you put into this, especially with the testing which I am realizing might be difficult for GUIs. 

I am still working on a review of your PR, but two things I have questions about after playing with it for a bit are:

1. When the GUI pops up, I seem to only show me folders. I don't know if this is specific to me or something inherent to the way the GUI is set up. It did this on windows and ubuntu and got the same result. I could see it being an issue for people trying to find the folder with the HTML files in it for example, because the HTML files wont render in the pop up, just the folder will, if that makes sense.  

2. It works great for me overall on windows, but on ubuntu 16.04 i get the following:

`Traceback (most recent call last):
  File "/home/myusername/Desktop/coding/Flaskerizer/gui_for_flaskerizer.py", line 4, in <module>
    import Tkinter as tk
ImportError: No module named 'Tkinter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/tkinter/__init__.py", line 36, in <module>
    import _tkinter
ImportError: No module named '_tkinter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/myusername/Desktop/coding/Flaskerizer/gui_for_flaskerizer.py", line 7, in <module>
    import tkinter as tk
  File "/usr/lib/python3.5/tkinter/__init__.py", line 38, in <module>
    raise ImportError(str(msg) + ', please install the python3-tk package')
ImportError: No module named '_tkinter', please install the python3-tk package`

Which was solved with:

`sudo apt-get install python3-tk`

Just a heads up, we might need to find a way to fix this so it works out of the box on linux 

I will be able to get to more review tomorrow. Thanks again for taking interest in the project a starting development on a cool feature. Since you have an active PR in I will put you down in the contributor list right away!

**Comment by etiontdn** [comment]
Thanks, yes i did make the window only show folders to make sure the user select folders, but in that perspective i think is better to show everything.
It's pretty hard to make tkinter out of the box, because it cant even be put in a pip requirements file,
Most of the python installs come with tkinter, but if a error like that pops up it's not hard to solve.

I will change the filedialog so it appears the files and folders. With that i may need to add error messages when the user selects a files instead wich will raise a error on the code.

I will  take a look and will make the changes as i can!

And yes the travis testing with gui is pretty hard but now it is done. It may add some seconds in testing but it will work 😄

**Comment by etiontdn** [comment]
Well. It is going to be harder than what i thought. the tkinter filedialog askdirectory is hardcoded for showing only directories and the filedialog askopenfilename is hardcoded for not allowing select of a directory so 
i can use askdirectory for the use selecting a folder but if i want him to see files i cant use askdirectoy.
If i want the user to see the files i can use askopenfilename but it doesnt let the user select a folder

There is how to make the askopenfilename to return the directory path instead of the file path but it needs to select a file first.
We can use that for html and js folders since the user can select the index.html file and a js file in the js directory
but in the static folder there are templates that use img, and css separated so... it will have a hard time using askopenfilename.
Probably the best would be to use askdirectory and select the main directory for the static folder
but can still use askopenfilename for html and js

Any ideas?

**Comment by brettvanderwerff** [comment]
@etiontdn  Its kind of a workaround but for now, but it is probably best to use askdirectory for the static and askopenfilename for the templates and js like you suggested if it works out in practice. As long as there is something in the popup that makes it clear to the user that they need to select one of the html files to designate that folder as the templates folder and one of the js files to designate that folder as the js folder (if I understand what you are saying correctly). In the README we can say that the gui is an option for users, but since it only seems to work without massaging in windows we should be clear that the gui is only available to windows users at this time. 

As far as tests go, I meant that I think it is hard for me to judge what a good test is for a gui. When I think of a good test I try to think of checking things that might break as the project grows in the future. Considering this, I am not sure what the most appropriate test is for the gui. 

I think its getting closer, you have been very engaged and I like how things are shaping up!

**Comment by brettvanderwerff** [comment]
This comment got buried, but the error I got on ubuntu 16.04 was:

`Traceback (most recent call last):
  File "/home/myusername/Desktop/coding/Flaskerizer/gui_for_flaskerizer.py", line 4, in <module>
    import Tkinter as tk
ImportError: No module named 'Tkinter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/tkinter/__init__.py", line 36, in <module>
    import _tkinter
ImportError: No module named '_tkinter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/myusername/Desktop/coding/Flaskerizer/gui_for_flaskerizer.py", line 7, in <module>
    import tkinter as tk
  File "/usr/lib/python3.5/tkinter/__init__.py", line 38, in <module>
    raise ImportError(str(msg) + ', please install the python3-tk package')
ImportError: No module named '_tkinter', please install the python3-tk package`

Which was solved with:

`sudo apt-get install python3-tk`

**Comment by etiontdn** [comment]
Ah, yes.
It can be included in the README if there any other person with these problems, but since the error tells you to install python3-tk is pretty simple to solve.

**Comment by brettvanderwerff** [comment]
@etiontdn 

I have been looking over some of you recent commits, looks like you are making progress on things!

One thing I have noticed is that some of the comments are hard to read. I know you said this was not your strong point, and that is fine, but one thing you can do to improve this is try to imagine what the code looks like to someone that did not write it. Also read your comments out loud, this will help you find errors. Its hard to type out comments and get it right on the first try. I always have to read things out loud and revise. 

For example:

"Select the a .js file, one in the js folder if there is one"

I think you would have caught that this does not read right if you read it aloud. 

There are spelling errors and odd capitalization throughout some some of the comments, which should be easy fixes.. Are you using an IDE? Most of them check spelling. If I develop outside of an IDE, I run my code comments through word or something that has spell check functionality. Clear documentation is *extremely* important and can make the difference between whether someone uses the flaskerizer or not. Good documentation not only helps users but can help other developers that need to understand what your code does in order to diagnose issues. Try to be clear, but concise. You can also be too verbose, which I am guilty of sometimes too.

"""This Class cointains everything related to the Graphical interface It contains some functions for the buttons and for organization"""

which has spelling errors and could be a bit more clear:

''' The ChooseFilesGUI class generates a popup graphical user interface (GUI) prompting the user to select paths pointing to folder content from the Bootstrap template that will be migrated to the 'templates', 'static', and javascript folders of the Flask app. This GUI functions as an alternative to requiring the user to manually enter these paths in the config.py file.
'''  


"Select a .js file, normally inside the js folder"

could be:

'''Select one JavaScript (.js) file from the template JavaScript folder"

This one might be too long because it has to fit, but you probably get the idea that it is a bit easier for a reader to understand what they must do. 

I'm trying to give you constructive criticism, so hopefully you are not offended. I know you have put a massive amount of work in the functionality of your contribution, but please remember that clear, spell checked documentation/comments are probably just as important.

**Comment by etiontdn** [comment]
Thanks for the feedback.

Specially thanks for making sure the spelling and documentation/comments are ok! 
I will try to give it more work since i'm pretty bad at it and i'm not a native speaker i will try my best to solve these!

The main motive of making a gui is to make it easier for people to use the program and bad comments and docstrings wont help.

**Comment by brettvanderwerff** [comment]
@etiontdn I thought you might not be a native speaker. Take your time on the comments if you need to and ask questions if you need to. Let me know how things are going when you are ready. I am working on my end to restructure the project to make it less cluttered. If I end up pushing the restructuring PR before we merge your PR, we might have to rebase your PR with master, but we can work through that together. Thank you again for your dedication to the flaskerizer.

**Comment by brettvanderwerff** [comment]
How is this going? Are you still engaged in this? It is okay if you are taking a break. I just wanted to drop in and see if you had any questions.

**Comment by etiontdn** [comment]
Yes, i was taking a break for a personal project, i didn't saw that the build failed, i will take a look.

**Comment by etiontdn** [comment]
I will close and make a new pull request

**Pull request closed without merging**
