### PR TITLE
Updated docker set up 

### PR DESCRIPTION
**Pull request by jmbriody**
I updated the docker set up so it would use an Alpine base image (much smaller). Also runs the flask app using uwsgi and nginx. 

You could probably change write_app.py and remove host='0.0.0.0' as it should still work in the docker on the local ip.

### CODE REVIEW

**Comment by brettvanderwerff** [comment]
@jmbriody Thanks for building this. I can't review right now because I am at work, but I'll take a look as soon as I get home! We're making good progress, a lot has changed in the past 24 hours, especially now that a coupe of people are working on it.

**Comment by jmbriody** [comment]
By default Flask uses the localhost/127.0.0.1 address--that address isn't
available outside of the machine itself. That also holds true within a
docker--something listening on 127.0.0.1 can only be accessed by other
processes within the docker. So it wouldn't be available externally. But
since Nginx is actually handling the web traffic from outside the docker it
can talk to uswgi and flask using the localhost address within the docker.

Should probably test it first though.

Jack

On Fri, May 18, 2018 at 6:24 PM, Brett Vanderwerff <notifications@github.com

**Comment by brettvanderwerff** [comment]
'By default Flask uses the localhost/127.0.0.1 address--that address isn't
available outside of the machine itself. That also holds true within a
docker--something listening on 127.0.0.1 can only be accessed by other
processes within the docker.'

so the run method of the flask object is host='127.0.0.1' by default, which is not visible other than on the local machine. We have to change to host='0.0.0.0' for the site to be publicly visible in deployment. 

I tested the current docker setup and I can view the site on my local machine regardless of whether host='0.0.0.0' is written in the run method of the flask object in write_app.py of if I delete the host='0.0.0.0' and just leave that method blank. I tested this both inside and outside docker. The only difference is having to navigate to either 127.0.0.1:5000 or 0.0.0.0:5000 in the browser.

If I am understanding this correctly, wouldn't it be more deployment ready if we leave the host set to 0.0.0.0? Sorry if I am not understanding this right.

**Comment by brettvanderwerff** [comment]
@jmbriody  For now I think I'll remove host='0.0.0.0.' and merge this. I can always make changes later if need be. Thanks for the explanation and all the work you did on this project. Especially since you are more advanced with docker and flask than I am, it was a huge help.

**Pull request merged**
